[env]
_.source = "{{exec(command='sops.exe --decrypt .enc.env')}}"

[tasks.test]
description = "Run tests"
run = "go test ./..."
[tasks.build]
description = "Build the application"
run = "go build -o ./bin/app/ ./..."

[tasks.lint]
description = "Run linter"
run = "golangci-lint run"

[tasks.format]
description = "Run formatter"
run = "golangci-lint fmt"
